### PR TITLE
[WIP] Modernize cookbook

### PR DESCRIPTION
**Pull request by damacus**

### CODE REVIEW

**Comment by damacus** [comment]
@kameghamegha how're you getting on with this one?

**Comment by kameghamegha** [comment]
Working on it @damacus. Just got back from vacation. Can you or another Sous Chef look over it for licenses and other requirements (beyond code requirements)?

**Comment by damacus** [comment]
Hah will do when I'm properly back from vacation

**Comment by josephholsten** [comment]
@damacus @kameghamegha I've been looking into failing tests in travis, but it looks like this fixes the tests. Is there anything I can do to help unblock this?

**Comment by damacus** [comment]
We've both been pulled in directions that are not this cookbook.
Anything to make this cookbook work and have tests would be awesome. 

You mind picking the baton up?

**Pull request merged**
